aggregator:
  # [required]
  flush_interval: 20s

api:
  # [required] api server address
  address: localhost:24424

sender:
  type: kinesis_streams
  stream_name: itkq-kinesis-agent-test
  forward_proxy_url: 

state:
  state_filepath: /tmp/kinesis-agent-go/test.state

watcher:
  # [required] watching paths
  watch_paths: 
    - /tmp/kinesis-agent-go/test*.log
    - /tmp/kinesis-agent-go/hoge.log

  # [required] 
  read_file_interval: 5s

  # [optional] path to output records which cannot send to kinesis because the blob is too big (highly recommended)
  unputtable_record_local_backup_path: "/tmp/kinesis-agent-go/unputtable"

  # [required] 
  lifetime_after_file_moved: 5s
